// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technical_tests_backend_ssr.Data;

#nullable disable

namespace technical_tests_backend_ssr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411161221_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Cuevas",
                            Email = "santiagobcuevas14@gmail.com",
                            Nombre = "Santiago",
                            Telefono = "1161970490"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Pérez",
                            Email = "lucia.perez@email.com",
                            Nombre = "Lucía",
                            Telefono = "1134567890"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Gómez",
                            Email = "martin.gomez@email.com",
                            Nombre = "Martín",
                            Telefono = "1145678901"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Rodríguez",
                            Email = "camila.rodriguez@email.com",
                            Nombre = "Camila",
                            Telefono = "1156789012"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Fernández",
                            Email = "julian.fernandez@email.com",
                            Nombre = "Julián",
                            Telefono = "1167890123"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "López",
                            Email = "sofia.lopez@email.com",
                            Nombre = "Sofía",
                            Telefono = "1178901234"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Díaz",
                            Email = "mateo.diaz@email.com",
                            Nombre = "Mateo",
                            Telefono = "1189012345"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Martínez",
                            Email = "valentina.martinez@email.com",
                            Nombre = "Valentina",
                            Telefono = "1190123456"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Sosa",
                            Email = "tomas.sosa@email.com",
                            Nombre = "Tomás",
                            Telefono = "1101234567"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Herrera",
                            Email = "agustina.herrera@email.com",
                            Nombre = "Agustina",
                            Telefono = "1112345678"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Marcas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Chevrolet"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Nissan"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Hyundai"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Volkswagen"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "BMW"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Audi"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Renault"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Peugeot"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Fiat"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MarcaId = 1,
                            Nombre = "Corolla"
                        },
                        new
                        {
                            Id = 2,
                            MarcaId = 2,
                            Nombre = "Focus"
                        },
                        new
                        {
                            Id = 3,
                            MarcaId = 3,
                            Nombre = "Cruze"
                        },
                        new
                        {
                            Id = 4,
                            MarcaId = 4,
                            Nombre = "Civic"
                        },
                        new
                        {
                            Id = 5,
                            MarcaId = 5,
                            Nombre = "Sentra"
                        },
                        new
                        {
                            Id = 6,
                            MarcaId = 6,
                            Nombre = "Elantra"
                        },
                        new
                        {
                            Id = 7,
                            MarcaId = 7,
                            Nombre = "Golf"
                        },
                        new
                        {
                            Id = 8,
                            MarcaId = 8,
                            Nombre = "Serie 3"
                        },
                        new
                        {
                            Id = 9,
                            MarcaId = 9,
                            Nombre = "A4"
                        },
                        new
                        {
                            Id = 10,
                            MarcaId = 10,
                            Nombre = "Clase C"
                        },
                        new
                        {
                            Id = 11,
                            MarcaId = 11,
                            Nombre = "Kangoo"
                        },
                        new
                        {
                            Id = 12,
                            MarcaId = 12,
                            Nombre = "208"
                        },
                        new
                        {
                            Id = 13,
                            MarcaId = 13,
                            Nombre = "Cronos"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.ToTable("Vehiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2020,
                            ModeloId = 1,
                            Precio = 5100000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2019,
                            ModeloId = 2,
                            Precio = 6300000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2021,
                            ModeloId = 3,
                            Precio = 5500000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2022,
                            ModeloId = 4,
                            Precio = 7000000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2018,
                            ModeloId = 5,
                            Precio = 5200000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            Anio = 2020,
                            ModeloId = 6,
                            Precio = 5600000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 7,
                            Anio = 2021,
                            ModeloId = 7,
                            Precio = 6500000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 8,
                            Anio = 2019,
                            ModeloId = 8,
                            Precio = 8000000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 9,
                            Anio = 2022,
                            ModeloId = 9,
                            Precio = 9000000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 10,
                            Anio = 2020,
                            ModeloId = 10,
                            Precio = 8500000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 11,
                            Anio = 2021,
                            ModeloId = 11,
                            Precio = 5100000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 12,
                            Anio = 2022,
                            ModeloId = 12,
                            Precio = 6200000m,
                            Stock = 9
                        },
                        new
                        {
                            Id = 13,
                            Anio = 2023,
                            ModeloId = 13,
                            Precio = 5900000m,
                            Stock = 11
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Modelo", b =>
                {
                    b.HasOne("technical_tests_backend_ssr.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Vehiculo", b =>
                {
                    b.HasOne("technical_tests_backend_ssr.Models.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Modelo", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
