// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technical_tests_backend_ssr.Data;

#nullable disable

namespace technical_tests_backend_ssr.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250411151835_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Cuevas",
                            Email = "santiagobcuevas14@gmail.com",
                            Nombre = "Santiago",
                            Telefono = "1161970490"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Pérez",
                            Email = "lucia.perez@email.com",
                            Nombre = "Lucía",
                            Telefono = "1134567890"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Gómez",
                            Email = "martin.gomez@email.com",
                            Nombre = "Martín",
                            Telefono = "1145678901"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Rodríguez",
                            Email = "camila.rodriguez@email.com",
                            Nombre = "Camila",
                            Telefono = "1156789012"
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Fernández",
                            Email = "julian.fernandez@email.com",
                            Nombre = "Julián",
                            Telefono = "1167890123"
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "López",
                            Email = "sofia.lopez@email.com",
                            Nombre = "Sofía",
                            Telefono = "1178901234"
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Díaz",
                            Email = "mateo.diaz@email.com",
                            Nombre = "Mateo",
                            Telefono = "1189012345"
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "Martínez",
                            Email = "valentina.martinez@email.com",
                            Nombre = "Valentina",
                            Telefono = "1190123456"
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Sosa",
                            Email = "tomas.sosa@email.com",
                            Nombre = "Tomás",
                            Telefono = "1101234567"
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Herrera",
                            Email = "agustina.herrera@email.com",
                            Nombre = "Agustina",
                            Telefono = "1112345678"
                        });
                });

            modelBuilder.Entity("technical_tests_backend_ssr.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 2020,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Precio = 5100000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Anio = 2019,
                            Marca = "Ford",
                            Modelo = "Focus",
                            Precio = 6300000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 3,
                            Anio = 2021,
                            Marca = "Chevrolet",
                            Modelo = "Cruze",
                            Precio = 5500000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 4,
                            Anio = 2022,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Precio = 7000000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 5,
                            Anio = 2018,
                            Marca = "Nissan",
                            Modelo = "Sentra",
                            Precio = 5200000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 6,
                            Anio = 2020,
                            Marca = "Hyundai",
                            Modelo = "Elantra",
                            Precio = 5600000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 7,
                            Anio = 2021,
                            Marca = "Volkswagen",
                            Modelo = "Golf",
                            Precio = 6500000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 8,
                            Anio = 2019,
                            Marca = "BMW",
                            Modelo = "Serie 3",
                            Precio = 8000000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 9,
                            Anio = 2022,
                            Marca = "Audi",
                            Modelo = "A4",
                            Precio = 9000000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 10,
                            Anio = 2020,
                            Marca = "Mercedes-Benz",
                            Modelo = "Clase C",
                            Precio = 8500000m,
                            Stock = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
